when@dev: &dev
    zenstruck_foundry:
        enable_auto_refresh_with_lazy_objects: true
        persistence:
            flush_once: true
        make_factory:
            default_namespace: 'App\DataFixtures\Factory'
        make_story:
            default_namespace: 'App\DataFixtures\Story'
        faker:
            locale: fr_FR

when@test: *dev
