services:
    php:
        volumes:
            - '.:/app:rw'
            - './infra/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro'
        depends_on: [ database, redis, smtp ]
        environment:
            MAILER_DSN: smtp://smtp:1025
            REDIS_URL: redis://redis
            DATABASE_URL: postgres://${POSTGRES_USER:-1z1-consent}:${POSTGRES_PASSWORD:-1z1-consent}@database:5432/${POSTGRES_DB:-1z1-consent}
            EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-"1z1 Consent <consent@un-zero-un.net>"}
            CADDY_SERVER_EXTRA_DIRECTIVES: tls /app/infra/docker/php/tls/cert.pem /app/infra/docker/php/tls/key.pem
            FRANKENPHP_WORKER_CONFIG: watch
            APP_ENV: ${APP_ENV:-dev}
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
        command: [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch" ]

    database:
        image: postgres:17
        volumes: [ database-data:/var/lib/postgresql/data ]
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-1z1-consent}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1z1-consent}
            POSTGRES_DB: ${POSTGRES_DB:-1z1-consent}
        ports:
            -   target: 5432
                published: ${DATABASE_PORT:-5432}
                protocol: tcp

    redis:
        image: redis:8
        ports:
            -   target: 6379
                published: ${REDIS_PORT:-6379}
                protocol: tcp

    smtp:
        image: mailhog/mailhog
        ports:
            -   target: 8025
                published: ${SMTP_PORT:-8025}
                protocol: tcp

volumes:
    database-data:
