services:
    php:
        volumes:
            - '.:/app:rw'
            - './infra/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro'
        depends_on: [ database, smtp, webpack ]
        environment:
            CADDY_SERVER_EXTRA_DIRECTIVES: ${CADDY_SERVER_EXTRA_DIRECTIVES:-tls /app/infra/docker/php/tls/cert.pem /app/infra/docker/php/tls/key.pem}
            FRANKENPHP_WORKER_CONFIG: watch
            APP_ENV: ${APP_ENV:-dev}
            DNT_ENABLED: !reset ${DNT_ENABLED:-}
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
        command: [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch" ]

    webpack:
        build:
            target: node
            args:
                EXTERNAL_USER_ID: ${EXTERNAL_USER_ID:-33}
        volumes:
            - '.:/app:rw'
        command: [ "yarn", "watch" ]

    database:
        image: postgres:17
        volumes: [ database-data:/var/lib/postgresql/data ]
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-1z1-consent}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1z1-consent}
            POSTGRES_DB: ${POSTGRES_DB:-1z1-consent}
        ports:
            -   target: 5432
                published: ${DATABASE_PORT:-5432}
                protocol: tcp

    smtp:
        image: mailhog/mailhog
        ports:
            -   target: 8025
                published: ${SMTP_PORT:-8025}
                protocol: tcp

    gotenberg:
        ports:
            -   target: 3000
                published: ${GOTENBERG_PORT:-3000}
                protocol: tcp

volumes:
    database-data:
